version: "3.8"

services:
  python-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mongodb://db:27017
      - OPENAI_API_KEY=${OPENAI_API_KEY} # Make sure to set this in .env file
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
